AllCops:
  NewCops: enable
Documentation:
  Exclude:
    - "**/railtie.rb"
    - "spec/**/*"
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
