AllCops:
  TargetRubyVersion: 3.2
Documentation:
  Exclude:
    - "**/railtie.rb"
    - "spec/**/*"
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 120
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - "redis_set_store.gemspec"
    - "spec/**/*"

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "spec/**/*"
